//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhooSoft.Auth.Resources.Strings
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources
    {
        #region Fields

        private static global::System.Globalization.CultureInfo resourceCulture;

        private static global::System.Resources.ResourceManager resourceMan;

        #endregion

        #region Constructors

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        #endregion

        #region Properties

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change Number.
        /// </summary>
        internal static string ChangNoTxt
        {
            get
            {
                return ResourceManager.GetString("ChangNoTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ContinueButton
        {
            get
            {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login Or Register.
        /// </summary>
        internal static string LoginOrRegTitle
        {
            get
            {
                return ResourceManager.GetString("LoginOrRegTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone number..
        /// </summary>
        internal static string LoginSubtitle
        {
            get
            {
                return ResourceManager.GetString("LoginSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle
        {
            get
            {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OTP Sent is Failed. Please Retry..
        /// </summary>
        internal static string OtpFailedMsg
        {
            get
            {
                return ResourceManager.GetString("OtpFailedMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t receive the OTP ? .
        /// </summary>
        internal static string OtpResentTxt
        {
            get
            {
                return ResourceManager.GetString("OtpResentTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resend OTP.
        /// </summary>
        internal static string OtpReTxt
        {
            get
            {
                return ResourceManager.GetString("OtpReTxt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the OTP Sent to .
        /// </summary>
        internal static string OtpSubTitle
        {
            get
            {
                return ResourceManager.GetString("OtpSubTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OTP Verification.
        /// </summary>
        internal static string OtpTitle
        {
            get
            {
                return ResourceManager.GetString("OtpTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZhooSoft.Auth.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry
        {
            get
            {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit
        {
            get
            {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }

        #endregion
    }
}
